[Model]
architecture = "pythae_VAE"

[Random_Search]
network_task = "reconstruction"
caps_directory = "/gpfswork/rech/krk/commun/datasets/adni/caps/caps_pet_uniform/"
tsv_path = "/gpfswork/rech/krk/usy14zi/vae_benchmark/random_search_vae/tsv_splits/6_fold"
preprocessing_json = "extract_pet_uniform_image.json"
first_layer_channels = [16, 32]
n_block_encoder = [4, 7]
feature_size = [0]
last_layer_conv = [true]
latent_space_size = [256, 512, 1024]
n_block_decoder = [4, 7]
last_layer_channels = [16, 32]
n_layer_per_block_encoder = [1, 3]
n_layer_per_block_decoder = [1, 3]
block_type = ["res"]
learning_rate = [1e-5, 1e-4, 1e-3]

[Computational]
gpu = true
n_proc = 10
batch_size = 8

[Data]
diagnoses = ["CN"]

[Optimization]
epochs = 200
optimizer = "Adamax"

[Cross_validation]
n_splits = 6